server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true